Document: gotiller
Title: Debian gotiller Manual
Author: <insert document author here>
Abstract: This manual describes what gotiller is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/gotiller/gotiller.sgml.gz

Format: postscript
Files: /usr/share/doc/gotiller/gotiller.ps.gz

Format: text
Files: /usr/share/doc/gotiller/gotiller.text.gz

Format: HTML
Index: /usr/share/doc/gotiller/html/index.html
Files: /usr/share/doc/gotiller/html/*.html
